// Generated by typings
// Source: my_typings/jsurl/index.d.ts
declare module 'jsurl' {
namespace JSURL {
  export function parse(str: any): any;
  export function stringify(obj :any):any;
}

export = JSURL;
}
