// Generated by typings
// Source: my_typings/store/index.d.ts
declare module 'store' {
namespace Store {
  export function set(key:any,value:any);
  export function get(key:any):any;
}

export = Store;
}
